# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_kracken"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = " command line parsing"
categories = ["command line argument parsing"]
keywords = ["fortran", "command line", "arguments"]
homepage = "https://github.com/urbanjost/M_kracken.git"

[build]
#auto-executables = true
#auto-examples = false
#auto-tests = false
#NO#module-naming = true          # Use default naming convention

[install]
library=true

[[test]]
name="test_suite"
source-dir="test"
main="test_suite_M_kracken.f90"
[test.dependencies]
M_framework    = { git = "https://github.com/urbanjost/M_framework.git" }

[dependencies]
M_strings      = { git = "https://github.com/urbanjost/M_strings.git" }
M_list         = { git = "https://github.com/urbanjost/M_list.git" }
M_args         = { git = "https://github.com/urbanjost/M_args.git" }
