# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_kracken"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = " command line parsing"
categories = ["command line argument parsing"]
keywords = ["fortran", "command line", "arguments"]
homepage = "https://github.com/urbanjost/M_kracken.git"

[install]
library="true"

[[test]]
name="test_suite"
source-dir="test"
main="test_suite_M_kracken.f90"
[test.dependencies]
M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }

[dependencies]
M_strings      = { git = "https://github.com/urbanjost/M_strings.git" }
M_list         = { git = "https://github.com/urbanjost/M_list.git" }
M_args         = { git = "https://github.com/urbanjost/M_args.git" }
