M_kracken: /home/urbanjs/venus/V600/github/M_kracken/src/M_kracken.f90 File Reference
M_kracken.f90 File Reference
Modules
module m_kracken
Functions/Subroutines
subroutine, public m_kracken::retrev (name, val, len, ier)
real(kind=dp) function, public m_kracken::dget (keyword)
real function, public m_kracken::rget (keyword)
integer function, public m_kracken::iget (keyword)
logical function, public m_kracken::lget (keyword)
character(len=:) function, allocatable, public m_kracken::sget (name, ilen)
real(kind=dp) function, dimension(:), allocatable, public m_kracken::dgets (keyword, ier)
integer function, dimension(:), allocatable, public m_kracken::igets (keyword, ier)
real function, dimension(:), allocatable, public m_kracken::rgets (keyword, ier)
logical function, dimension(:), allocatable, public m_kracken::lgets (keyword)
character(len=:) function, dimension(:), allocatable, public m_kracken::sgets (name, delim)
subroutine, public m_kracken::kracken (verb, string, error_return, style)
subroutine, public m_kracken::setprompts (verb, init)
subroutine, public m_kracken::dissect (verb, init, pars, error_return)
recursive subroutine, public m_kracken::parse (verb, string, allow, error_return)
subroutine, public m_kracken::store (name1, value1, allow1, ier)
integer function, private m_kracken::subscript_ (chars0)
subroutine, private m_kracken::menu (verb)
subroutine, public m_kracken::show (VERB_NAME0, VERBS_ONLY, IWIDE)
subroutine m_kracken::initd ()
subroutine, public m_kracken::test_suite_m_kracken ()
subroutine test_dget ()
subroutine test_dgets ()
subroutine test_dissect ()
subroutine test_iget ()
subroutine test_igets ()
subroutine test_kracken ()
subroutine test_lget ()
subroutine test_lgets ()
subroutine test_parse ()
subroutine test_retrev ()
subroutine test_rget ()
subroutine test_rgets ()
subroutine test_setprompts ()
subroutine test_sget ()
subroutine test_sgets ()
subroutine test_show ()
subroutine test_store ()
subroutine, public m_kracken::cmd_args_to_dictionary (verb)
subroutine ifnull ()
subroutine, public m_kracken::print_kracken_dictionary (header)
Variables
logical, public m_kracken::stop_command =.false.
integer, parameter, public m_kracken::ipvalue =4096*16
integer, parameter, public m_kracken::ipverb =20
integer, parameter m_kracken::dp = kind(0.d0)
integer, parameter m_kracken::k_int = SELECTED_INT_KIND(9)
integer, parameter m_kracken::k_dbl = SELECTED_REAL_KIND(15, 300)
character(len=:), dimension(:), allocatable m_kracken::dict_vals
character(len=:), dimension(:), allocatable m_kracken::dict_verbs
integer(kind=k_int), dimension(:), allocatable m_kracken::dict_lens
integer(kind=k_int), dimension(:), allocatable m_kracken::dict_calls
character(len=1), save, public m_kracken::kracken_comment ='#'
character(len=:), allocatable, save, public m_kracken::leftover
integer, save, public m_kracken::current_command_length =0
character(len=:), dimension(:), allocatable, save, public m_kracken::unnamed
character(len=10), save, public m_kracken::kracken_method ='kracken'
Function/Subroutine Documentation
ifnull()
subroutine cmd_args_to_dictionary::ifnull private
References m_kracken::sget(), and m_kracken::store().
test_dget()
subroutine test_suite_m_kracken::test_dget
References m_kracken::dget(), and m_kracken::store().
test_dgets()
subroutine test_suite_m_kracken::test_dgets
References m_kracken::dgets(), and m_kracken::store().
test_dissect()
subroutine test_suite_m_kracken::test_dissect private
References m_kracken::dissect(), m_kracken::iget(), m_kracken::rget(), and m_kracken::sget().
test_iget()
subroutine test_suite_m_kracken::test_iget private
References m_kracken::iget(), and m_kracken::store().
test_igets()
subroutine test_suite_m_kracken::test_igets private
References m_kracken::igets(), and m_kracken::store().
test_kracken()
subroutine test_suite_m_kracken::test_kracken private
test_lget()
subroutine test_suite_m_kracken::test_lget private
References m_kracken::lget(), and m_kracken::store().
test_lgets()
subroutine test_suite_m_kracken::test_lgets private
References m_kracken::lgets(), and m_kracken::store().
test_parse()
subroutine test_suite_m_kracken::test_parse private
References m_kracken::iget(), m_kracken::parse(), m_kracken::rget(), and m_kracken::sget().
test_retrev()
subroutine test_suite_m_kracken::test_retrev private
References m_kracken::kracken(), and m_kracken::retrev().
test_rget()
subroutine test_suite_m_kracken::test_rget private
References m_kracken::dget(), m_kracken::rget(), and m_kracken::store().
test_rgets()
subroutine test_suite_m_kracken::test_rgets private
References m_kracken::rgets(), and m_kracken::store().
test_setprompts()
subroutine test_suite_m_kracken::test_setprompts private
test_sget()
subroutine test_suite_m_kracken::test_sget private
References m_kracken::sget(), and m_kracken::store().
test_sgets()
subroutine test_suite_m_kracken::test_sgets private
References m_kracken::sgets(), and m_kracken::store().
test_show()
subroutine test_suite_m_kracken::test_show private
test_store()
subroutine test_suite_m_kracken::test_store private
References m_kracken::dget(), m_kracken::iget(), m_kracken::lget(), m_kracken::rget(), m_kracken::sget(), and m_kracken::store().